function g = forward(q)
q1 = q(1);
q2 = q(2);
q3 = q(3);
gamma = q(4);
theta = q(5);
alpha = q(6);
D = 0.5;
L = 0.058;
g =[[cos(q2)*sin(alpha)*cos(theta)*sin(q1) - sin(q1)*sin(q2)*(sin(gamma + theta)*sin(theta) + cos(gamma + theta)*cos(alpha)*cos(theta)) - cos(q1)*(cos(gamma + theta)*sin(theta) - sin(gamma + theta)*cos(alpha)*cos(theta)), cos(q1)*(cos(gamma + theta)*cos(theta) + sin(gamma + theta)*cos(alpha)*sin(theta)) + sin(q1)*sin(q2)*(sin(gamma + theta)*cos(theta) - cos(gamma + theta)*cos(alpha)*sin(theta)) + cos(q2)*sin(alpha)*sin(q1)*sin(theta), sin(gamma + theta)*cos(q1)*sin(alpha) - cos(alpha)*cos(q2)*sin(q1) - cos(gamma + theta)*sin(alpha)*sin(q1)*sin(q2), (L*cos(gamma + theta)*sin(q1)*sin(q2)*(cos(alpha) - 1))/alpha - (L*sin(gamma + theta)*cos(q1)*(cos(alpha) - 1))/alpha - (L*cos(q2)*sin(alpha)*sin(q1))/alpha - cos(q2)*sin(q1)*(D - q3)]
[                                                                                                   - cos(q2)*(sin(gamma + theta)*sin(theta) + cos(gamma + theta)*cos(alpha)*cos(theta)) - sin(alpha)*cos(theta)*sin(q2),                                                                                                      cos(q2)*(sin(gamma + theta)*cos(theta) - cos(gamma + theta)*cos(alpha)*sin(theta)) - sin(alpha)*sin(q2)*sin(theta),                                                         cos(alpha)*sin(q2) - cos(gamma + theta)*cos(q2)*sin(alpha),                                                                                 sin(q2)*(D - q3) + (L*sin(alpha)*sin(q2))/alpha + (L*cos(gamma + theta)*cos(q2)*(cos(alpha) - 1))/alpha]
[cos(q1)*sin(q2)*(sin(gamma + theta)*sin(theta) + cos(gamma + theta)*cos(alpha)*cos(theta)) - sin(q1)*(cos(gamma + theta)*sin(theta) - sin(gamma + theta)*cos(alpha)*cos(theta)) - cos(q1)*cos(q2)*sin(alpha)*cos(theta), sin(q1)*(cos(gamma + theta)*cos(theta) + sin(gamma + theta)*cos(alpha)*sin(theta)) - cos(q1)*sin(q2)*(sin(gamma + theta)*cos(theta) - cos(gamma + theta)*cos(alpha)*sin(theta)) - cos(q1)*cos(q2)*sin(alpha)*sin(theta), sin(gamma + theta)*sin(alpha)*sin(q1) + cos(alpha)*cos(q1)*cos(q2) + cos(gamma + theta)*cos(q1)*sin(alpha)*sin(q2), cos(q1)*cos(q2)*(D - q3) - (L*sin(gamma + theta)*sin(q1)*(cos(alpha) - 1))/alpha + (L*cos(q1)*cos(q2)*sin(alpha))/alpha - (L*cos(gamma + theta)*cos(q1)*sin(q2)*(cos(alpha) - 1))/alpha]
[                                                                                                                                                                                                                      0,                                                                                                                                                                                                                       0,                                                                                                                  0,                                                                                                                                                                                       1]];
end