function J = jacob(q)
q1 = q(1);
q2 = q(2);
q3 = q(3);
gamma = q(4);
theta = q(5);
alpha = q(6);
D = 0.5;
L = 0.058;
J =[[ 0,        0,  cos(q2)*sin(q1),                0,            ((2*L*(cos(alpha)/2 - 1/2) + alpha*q3*sin(alpha) - D*alpha*sin(alpha))*(cos(gamma)*cos(q1)*cos(theta) - cos(q1)*sin(gamma)*sin(theta) + cos(gamma)*sin(q1)*sin(q2)*sin(theta) + cos(theta)*sin(gamma)*sin(q1)*sin(q2)))/alpha, (L*(cos(q2)*sin(alpha)*sin(q1) - cos(q1)*cos(theta)*sin(gamma) - cos(gamma)*cos(q1)*sin(theta) + cos(alpha)*cos(gamma)*cos(q1)*sin(theta) + cos(alpha)*cos(q1)*cos(theta)*sin(gamma) + cos(gamma)*cos(theta)*sin(q1)*sin(q2) - sin(gamma)*sin(q1)*sin(q2)*sin(theta) - cos(alpha)*cos(gamma)*cos(theta)*sin(q1)*sin(q2) + cos(alpha)*sin(gamma)*sin(q1)*sin(q2)*sin(theta)))/alpha^2 - (D - q3)*(cos(gamma)*cos(q1)*sin(theta) + cos(q1)*cos(theta)*sin(gamma) - cos(gamma)*cos(theta)*sin(q1)*sin(q2) + sin(gamma)*sin(q1)*sin(q2)*sin(theta)) - (L*cos(q2)*sin(q1))/alpha]
[ 0,        0,         -sin(q2),                0,                                                                                                                                 - sin(gamma + theta)*cos(q2)*sin(alpha)*(D - q3) - (2*L*sin(alpha/2)^2*sin(gamma + theta)*cos(q2))/alpha,                                                                                                                                                                                                                                                                                               cos(q2)*(D - q3)*(cos(gamma)*cos(theta) - sin(gamma)*sin(theta)) - (L*(sin(alpha)*sin(q2) - cos(gamma)*cos(q2)*cos(theta) + cos(q2)*sin(gamma)*sin(theta) + cos(alpha)*cos(gamma)*cos(q2)*cos(theta) - cos(alpha)*cos(q2)*sin(gamma)*sin(theta)))/alpha^2 + (L*sin(q2))/alpha]
[ 0,        0, -cos(q1)*cos(q2),                0,                  ((2*L*sin(alpha/2)^2 - alpha*q3*sin(alpha) + D*alpha*sin(alpha))*(sin(gamma)*sin(q1)*sin(theta) - cos(gamma)*cos(theta)*sin(q1) + cos(gamma)*cos(q1)*sin(q2)*sin(theta) + cos(q1)*cos(theta)*sin(gamma)*sin(q2)))/alpha, (L*cos(q1)*cos(q2))/alpha - (L*(cos(q1)*cos(q2)*sin(alpha) + cos(gamma)*sin(q1)*sin(theta) + cos(theta)*sin(gamma)*sin(q1) + cos(gamma)*cos(q1)*cos(theta)*sin(q2) - cos(alpha)*cos(gamma)*sin(q1)*sin(theta) - cos(alpha)*cos(theta)*sin(gamma)*sin(q1) - cos(q1)*sin(gamma)*sin(q2)*sin(theta) - cos(alpha)*cos(gamma)*cos(q1)*cos(theta)*sin(q2) + cos(alpha)*cos(q1)*sin(gamma)*sin(q2)*sin(theta)))/alpha^2 - (D - q3)*(cos(gamma)*sin(q1)*sin(theta) + cos(theta)*sin(gamma)*sin(q1) + cos(gamma)*cos(q1)*cos(theta)*sin(q2) - cos(q1)*sin(gamma)*sin(q2)*sin(theta))]
[ 0, -cos(q1),                0, -cos(q2)*sin(q1), cos(alpha)*cos(q2)*sin(q1) - cos(q2)*sin(q1) - cos(gamma)*cos(q1)*sin(alpha)*sin(theta) - cos(q1)*sin(alpha)*cos(theta)*sin(gamma) + cos(gamma)*sin(alpha)*cos(theta)*sin(q1)*sin(q2) - sin(alpha)*sin(gamma)*sin(q1)*sin(q2)*sin(theta),                                                                                                                                                                                                                                                                                                                                                                                                                               cos(gamma)*cos(q1)*cos(theta) - cos(q1)*sin(gamma)*sin(theta) + cos(gamma)*sin(q1)*sin(q2)*sin(theta) + cos(theta)*sin(gamma)*sin(q1)*sin(q2)]
[-1,        0,                0,          sin(q2),                                                                                                                       sin(q2) - cos(alpha)*sin(q2) + cos(gamma)*cos(q2)*sin(alpha)*cos(theta) - cos(q2)*sin(alpha)*sin(gamma)*sin(theta),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  sin(gamma + theta)*cos(q2)]
[ 0, -sin(q1),                0,  cos(q1)*cos(q2), cos(q1)*cos(q2) - cos(alpha)*cos(q1)*cos(q2) - cos(gamma)*sin(alpha)*sin(q1)*sin(theta) - sin(alpha)*cos(theta)*sin(gamma)*sin(q1) - cos(gamma)*cos(q1)*sin(alpha)*cos(theta)*sin(q2) + cos(q1)*sin(alpha)*sin(gamma)*sin(q2)*sin(theta),                                                                                                                                                                                                                                                                                                                                                                                                                               cos(gamma)*cos(theta)*sin(q1) - sin(gamma)*sin(q1)*sin(theta) - cos(gamma)*cos(q1)*sin(q2)*sin(theta) - cos(q1)*cos(theta)*sin(gamma)*sin(q2)]];
end